### ISSUE TITLE
Can we add a flag to allow self-signed certs?

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [cloudfoundry/routing-api-cli#5]
For the rtr cli calls, can we have a flag `--skip-ssl-validation` that would allow self-signed certs.

For example

```
rtr list --api api.some-pcf-installation.com --client-id cloud_controller --client-secret some_client_secret --oauth-url https://some-uaa-server.com --skip-ssl-validation
```

Majority of our test envs don't have issued certs so this would be very beneficial for testing. Similarly, we cannot easily obtain the cc client creds on public envs like run.pivotal.io

**Comment by shalako** [comment]
Hello, we have  story for this already in our backlog. https://www.pivotaltracker.com/story/show/98052506

**Comment by xtreme-sameer-vohra** [comment]
Thanks Shannon
