### ISSUE TITLE
only hits experimental endpoints for HTTP routes

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/routing-api-cli#8]
This only does CRUD on the HTTP route endpoints. There is no way to get the TCP routes from CLI.

**Comment by shashwathi** [comment]
@jtarchie : 

Thank you filing this issue. I agree that `rtr` CLI serves pretty minimal set of features but CF CLI has support for creating, listing and deleting TCP routes. Any reason to use rtr CLI instead of CF CLI? 

Regards
Shash

**Comment by shubhaat** [comment]
@jtarchie We do not intend to add more functionality to the rtr CLI in the near term. Closing this issue for now, since it's been open for a year without much activity.
