### ISSUE TITLE
UAA library is logging to STDOUT

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/routing-api-cli#9]
The UAA client is logging to STDOUT, this makes it difficult to parse just the JSON api results.

For example:

```
$ rtr list
{"timestamp":"1495992236.006312847","source":"rtr","message":"rtr.uaa-client.fetch-token-from-uaa-end","log_level":1,"data":{"session":"3","status-code":200}}
[{"route":"api.pinapple.cf-app.com/routing","port":3000,"ip":"10.0.16.10","ttl":120,"log_guid":"routing_api","modification_tag":{"guid":"93078894-7a66-4bd9-733b-0b6178e8e805","index":2634}}]
```

**Comment by shashwathi** [comment]
@jtarchie : 

Thank you for filing this issue. I agree that parsing routes can be difficult in the above output. UAA client should output log lines only if `RTR_TRACE` is set to true.

@shalako : This looks like a bug. We can update this behavior on all CLI commands.

Regards
Shash

**Comment by aaronshurley** [comment]
This story has been accepted. Closing.
